server.port=8080
#jdbc:mysql://: Giao thức kết nối của Java đến hệ quản trị MySQL.

spring.datasource.url=jdbc:mysql://localhost:3306/BookFood?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=namliminon
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Kết nối đến DB